// Generated by CoffeeScript 1.7.1
(function() {
  var fs, show_location;

  fs = require('fs');

  show_location = function(f_str) {
    console.log(f_str);
    if (f_str[2] === '區') {
      return fs.readFile('../data/fond_data/' + f_str, function(err, data) {
        var d, _i, _len, _ref, _results;
        if (err) {
          console.log(err);
        }
        _ref = JSON.parse(data);
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          d = _ref[_i];
          _results.push(console.log(d.Title));
        }
        return _results;
      });
    }
  };

  fs.readdir('../data/fond_data/', function(err, files) {
    var f, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      f = files[_i];
      _results.push(show_location(f));
    }
    return _results;
  });

}).call(this);
